jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - aws-s3/copy:
          arguments: '--dryrun'
          from: ~/project/index.html
          to: 's3://sample.dummy-project.com'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: ~/project/pic_trulli.jpg
          to: 's3://sample.dummy-project.com'
      
      
orbs:
  aws-s3: circleci/aws-s3@2.0.0
version: 2.1

workflows:
  deployment:
    jobs:
      - build:
          context: dummy